### ISSUE TITLE
Add tax codes on billing

### ISSUE THREAD

**Issue by Ninjeneer** [sap-labs-france/ev-server#1029]

**Comment by ClaudeROSSI** [comment]
The life cycle of taxes (and tax codes) is quite strict and must be seen as a prerequisites to billing activities. It should not be possible to generate an invoice if the tax codes are not properly declared.
In other words, the **tax codes should NOT be an entity** on the eMobility side. We should consider them as a prerequisite to the activation of the billing of the EV charging sessions.

With our STRIPE integration, the admin enters (centrally) the tax rate to use when charging transactions. With our first version, the tax rate is unique and defined in the billing settings. We will have for sure to make this more flexible (e.g.: per site and per product (energy / parking))

So, with the STRIPE integration, we do not manage on our side a list of tax codes. We simply make sure the external 'account' such as the STRIPE account is properly configured and **only** activate the billing of transactions after checking the **prerequisites**.

I will open new issues, to make sure the prerequisites are checked on a regular basis (everyday?) and clarify how to handle the situation where a tax rate gets archived and a new one needs to be used for subsequent invoices.
