### ISSUE TITLE
GitHub > CI: Unit Test fails

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-server#1649]
Could you please check?
Thanks!

https://github.com/LucasBrazi06/ev-server/runs/824418246?check_suite_focus=true

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/b00d01bb-82b4-49e2-9af0-810fb5d1310d)

**Comment by jerome-benoit** [comment]
Cannot reproduce locally but it happens on GitHub action all the time.
