### ISSUE TITLE
Security > WhiteSource: Fix high prio issues

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-server#1827]
https://saas.whitesourcesoftware.com/Wss/WSS.html#!alertsReport

Compensation Assistant![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/3fc4da17-8d32-4636-9a17-fbd3238cb0e5)

**Comment by jerome-benoit** [comment]
At that message date, no high priority issues on: 
[ ] ev-server
[ ] ev-dashboard
[ ] ev-mobile (not yet scanned)
[ ] ev-simulator (not yet in a pipeline but kept up2date)
