### ISSUE TITLE
Smart Charging - Handle charging stations, which refuse the charging profile

### ISSUE THREAD

**Issue by OliveGerste** [sap-labs-france/ev-server#1862]

**Comment by LucasBrazi06** [comment]
Retry 3 times to push the charging profiles and if failed, exclude the charging station from the Smart Charging, send a notification to the Admins and retry again to apply the Smart Charging on the Site Area.

**Comment by jerome-benoit** [comment]
I think axios is used by the SetChargingProfile OCPP command, so it already retries 3 (tunable) times before throwing an error.

**Comment by LucasBrazi06** [comment]
> I think axios is used by the SetChargingProfile OCPP command, so it already retries 3 (tunable) times before throwing an error.

Perfect so no need to check that part then 👍

**Comment by jerome-benoit** [comment]
In fact, axios will not retry because it's not an HTTP error ;) 
The retry condition lie in the upper network layer protocol.

**Comment by LucasBrazi06** [comment]
> In fact, axios will not retry because it's not an HTTP error ;)
> The retry condition lie in the upper network layer protocol.

Perfect so we need to check that part then 👍 :-)
