### ISSUE TITLE
Edit Site Area Bug

### ISSUE THREAD

**Issue by mahdibenromdhane** [sap-labs-france/ev-server#1893]
Edit site area popup empty for basic user after create. 

![image.png](https://images.zenhubusercontent.com/5e1f2e3de924e3a56bb760f1/16b58f5c-bb93-4ec7-a69d-b7137870992d)

**Comment by OliveGerste** [comment]
@mahdibenromdhane 
It is working in prod and in local environment, but somehow not in qa: 
![image](https://user-images.githubusercontent.com/33114317/102092772-b155d500-3e20-11eb-8c0d-b8b6ed6d180d.png)

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane
> It is working in prod and in local environment, but somehow not in qa:
> ![image](https://user-images.githubusercontent.com/33114317/102092772-b155d500-3e20-11eb-8c0d-b8b6ed6d180d.png)

Cannot reproduce on QA, seems to be working on my side. @OliveGerste did you make sure that the basic test-user is a site admin ?
