### ISSUE TITLE
Smart Charging - Optimizer cannot handle arrivals of the previous day

### ISSUE THREAD

**Issue by OliveGerste** [sap-labs-france/ev-server#1906]
If a car plugs at 23:45., the optimizer will get a negative value for timeStampArrival after midnight.
It is not capable of handling this. 
@LucasBrazi06 How should we handle this? Setting the value back to 0? 
Or should I ask Oliver for a solution proposal?

**Comment by LucasBrazi06** [comment]
> If a car plugs at 23:45., the optimizer will get a negative value for timeStampArrival after midnight.
> It is not capable of handling this.
> @LucasBrazi06 How should we handle this? Setting the value back to 0?
> Or should I ask Oliver for a solution proposal?

Ask Oliver if he can improve this and let's see what he will propose.
