### ISSUE TITLE
Perfs: Tests with 100, 1000, 10000, 100000 Charging Stations

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-server#194]
- Goal is to provide a report that we can show to the customers that contains:
* Charger Connections with 100, 1000, 10000, 100000 (at once) 
* Charger Transactions with 100, 1000, 10000, 100000

Monitor the traffic/cpu/mem for each topic and generate charts so we can compare each load.

You can create a dedicated tenant in production so we can test real perfs and also the UI with this amount of data.

Try also to provide when creating the chargers, valid GPS coordinates so we can show them in SAC

**Comment by jerome-benoit** [comment]
ev-simulator have been greatly improved since to permit to run load tests from AWS. 
There's two much changes to list but the relevant one here is: make charging station simulation code self-contained to permit it to run inside a node.js worker.

**Comment by LucasBrazi06** [comment]
> ev-simulator have been greatly improved since to permit to run load tests from AWS.
> There's two much changes to list but the relevant one here is: make charging station simulation code self-contained to permit it to run inside a node.js worker.

Excellent!
Is there a tool to generate a ramp up traffic (1 -> 1000 chargers in 30 mins) + analyzing the response time afterward (chart)?

**Comment by jerome-benoit** [comment]
ev-simulator can generate log with the performance measurement on currently a few request/response types (SRPC). It's easy to extend it to more calls with a bit of code factorisation and more sensible performance pinpoint hooks. The logger winston can be configured to push the log in logstash for example to do the analysis afterwards.  

The ramp up can be simulated by deployment pipeline calls loop with awscli in a shell script. 

But I will have to redo the ev-simulator pipeline because of excessive cleanups on AWS ;)

**Comment by jerome-benoit** [comment]
I think that using winston also on ev-server to log on the console all the performance measurement you've added will permit to easily push the performance measurement to tools for analysis. 
I think that winston can probably replace most of the console.log calls on ev-server.

**Comment by LucasBrazi06** [comment]
> I think that using winston also on ev-server to log on the console all the performance measurements you've added will permit to easily push the performance measurement to tools for analysis.
> I think that winston can probably replace most of the console.log() calls on ev-server.

Ok let me know, you see my point, I want a beautiful curve that will pinpoint perfs issues.

**Comment by LucasBrazi06** [comment]
> I think that using winston also on ev-server to log on the console all the performance measurements you've added will permit to easily push the performance measurement to tools for analysis.
> I think that winston can probably replace most of the console.log() calls on ev-server.

Could you show me how it'll look like in the end ?

**Comment by LucasBrazi06** [comment]
> ev-simulator can generate log with the performance measurement on currently a few request/response types (SRPC). It's easy to extend it to more calls with a bit of code factorisation and more sensible performance pinpoint hooks. The logger winston can be configured to push the logs in logstash for example to do the analysis afterwards.
> 
> The ramp up can be simulated by deployment pipeline calls loop with awscli in a shell script.
> 
> But I will have to redo the ev-simulator pipeline because of excessive cleanups on AWS ;)

Ok let me know, you see my point, I want a beautiful curve that will pinpoint perfs issues.

**Comment by jerome-benoit** [comment]
You choose the output format on winston like JSON, logstash, simple, splat, etc.. You can combine them, make your own, etc. 
You then apply a format to an output transport like the console, files, external tools, etc. 

For example with simple format combined with string interpolation: 
info: 11/11/2020, 7:11:22 PM CS-SCHNEIDER-0001 Statistics: {"BootNotification":{"countRequest":4},"StatusNotification":{"countRequest":14},"GetConfiguration":{"countRequest":2,"countResponse":2},"Reset":{"countRequest":1,"countResponse":1},"Heartbeat":{"countRequest":4},"RemoteStartTransaction":{"countRequest":1,"countResponse":1},"StartTransaction":{"countRequest":2},"MeterValues":{"countRequest":8,"countTime":4,"minTime":0.630136,"maxTime":8.26254,"totalTime":10.757673,"avgTime":2.68941825}}

I'm pretty sure you can also feed Dynatrace. 

If the hosting platform target is SCP, Dynatrace do already the performance analysis issue on ev-server.

**Comment by LucasBrazi06** [comment]
> You choose the output format on winston like JSON, logstash, simple, splat, etc.. You can combine them, make your own, etc.
> You then apply a format to an output transport like the console, files, external tools, etc.
> 
> For example with simple format combined with string interpolation:
> `info: 11/11/2020, 7:11:22 PM CS-SCHNEIDER-0001 Statistics: {"BootNotification":{"countRequest":4},"StatusNotification":{"countRequest":14},"GetConfiguration":{"countRequest":2,"countResponse":2},"Reset":{"countRequest":1,"countResponse":1},"Heartbeat":{"countRequest":4},"RemoteStartTransaction":{"countRequest":1,"countResponse":1},"StartTransaction":{"countRequest":2},"MeterValues":{"countRequest":8,"countTime":4,"minTime":0.630136,"maxTime":8.26254,"totalTime":10.757673,"avgTime":2.68941825}}`
> 
> I'm pretty sure you can also feed Dynatrace.
> 
> If the hosting platform target is SCP, Dynatrace do already the performance analysis issue on ev-server.

Ok but this is more an aggregation after a load test than a trace like in the console.

**Comment by jerome-benoit** [comment]
Gathering measurement done is the starting point for performance analysis if you do not use tools like clinic or Dynatrace that instrument transparently, gather, analyse, etc.

**Comment by LucasBrazi06** [comment]
> Gathering measurement done is the starting point for performance analysis if you do not use tools like clinic or Dynatrace that instrument transparently, gather, analyse, etc.

Ok so we keep the logs in the console then.

**Comment by jerome-benoit** [comment]
Latest ev-simulator code improvements have allowed it to now easily simulate 100 000 (and more) charging stations on SCP.
