### ISSUE TITLE
Bug in displaying Images in car Catalog carousel

### ISSUE THREAD

**Issue by mahdibenromdhane** [sap-labs-france/ev-server#1942]
![image.png](https://images.zenhubusercontent.com/5e1f2e3de924e3a56bb760f1/a450b959-0b31-4e28-8dea-8262a21d8ad7)

**Comment by OliveGerste** [comment]
@mahdibenromdhane  
Image is displayed, when it is available
When no image is available, there could be a message or a standard no image icon 
(If this is not needed, it can be closed)

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane
> Image is displayed, when it is available
> When no image is available, there could be a message or a standard no image icon
> (If this is not needed, it can be closed)

Yes you'r right, I think the tab Images should not be displayed at all if there is no images to display in the caroussel. I will push a fix.

**Comment by LucasBrazi06** [comment]
> Yes you'r right, I think the tab Images should not be displayed at all if there is no images to display in the caroussel. I will push a fix.

I would prefer to keep the tab with a message like in the empty list that replaces the carousel control saying that there is no car image to display.

**Comment by mahdibenromdhane** [comment]
> > Yes you'r right, I think the tab Images should not be displayed at all if there is no images to display in the caroussel. I will push a fix.
> 
> I would prefer to keep the tab with a message like in the empty list that replaces the carousel control saying that there is no car image to display.

Ok.
