### ISSUE TITLE
Mock-Up Approuter Application

### ISSUE THREAD

**Issue by captaineaglex** [sap-labs-france/ev-server#1949]
- [x] create an mock-up approuter app

- [x] integrate authentication through SAP IdP

- [x] put a debugger to observe JWTs

**Comment by jerome-benoit** [comment]
Can you please make a PR containing your current work on the approuter repository? 

Thanks.

**Comment by captaineaglex** [comment]
I have made the pull requested as requested. It is on the ev-sap-app-router repository.

**Comment by jerome-benoit** [comment]
Could you please update your work in progress branch on ev-sap-app-router repository? 

Thanks.

**Comment by captaineaglex** [comment]
I have pushed the latest files to the respective repository. Thanks a lot!
