### ISSUE TITLE
No Access rights or repository don't exist

### ISSUE THREAD

**Issue by JRGONGk** [sap-labs-france/ev-server#1979]
I am trying to deploy ev-server using docker and I have added ev_mongo in hosts file with ip 127.0.0.1 but I am unable to clone the repository in my src files.
![2020-12-15](https://user-images.githubusercontent.com/51272647/102201707-791bc880-3eec-11eb-8132-9cb313a757e3.png)

Please help me with this!
I am using ubuntu 18

**Comment by JRGONGk** [comment]
I have just added a keypair to git hub.

**Comment by jerome-benoit** [comment]
You don't need them to run ev-server.

**Comment by JRGONGk** [comment]
It is mentioned to start the container, run command "make server", when I use this command it shows failed to clone repositories.

**Comment by jerome-benoit** [comment]
> It is mentioned to start the container, run command "make server", when I use this command it shows failed to clone repositories.

I repeat: 'You don't need them to run ev-server.'  

And never ever work as root under *nix operating system.

Could your please wait for being officially onboarded on the e-mobility project by SAP Labs France like I've  already told you twice to have all the inputs you need to setup your dev environment properly?

**Comment by JRGONGk** [comment]
How can I officially onboard on the e-mobility project by sap labs? Is it some kind of license or I just simply needs to learn something? Do I need to buy something?
