### ISSUE TITLE
 mochatest

### ISSUE THREAD

**Issue by JRGONGk** [sap-labs-france/ev-server#2004]
Hi!,
My ev-dashboard is connected with ev-server. But whenever I run npm run  mochatest:createContext it always show an error "  Error: connect ECONNREFUSED 127.0.0.1:8081". I have already came this far. Please help with this issue.
Thanks in advance!

![2021-01-06](https://user-images.githubusercontent.com/51272647/103733676-4909a600-5010-11eb-8ca2-38e99cae9e02.png)

**Comment by rccess** [comment]
i am facing same issue, why this is closed with giving any clue , please do advise

**Comment by LucasBrazi06** [comment]
Sorry guys, I'm currently on holiday but I'll try to help you.
Have you created the local.json file needed to run the unit tests in directory 'test/config/'?

**Comment by rccess** [comment]
I have local.json under the test/config 
And the data under the local.json according to describe but it is getting 500 internal server error  in return

**Comment by LucasBrazi06** [comment]
It seems trying to access the backend without success but managed to connect to the DB.
Have you checked the logs or try to put a breakpoint on the use case that failed?

**Comment by LucasBrazi06** [comment]
Closed for inactivity reason.
