### ISSUE TITLE
Billing > STRIPE Setup - Default Values are confusing

### ISSUE THREAD

**Issue by ClaudeROSSI** [sap-labs-france/ev-server#2022]
![image](https://user-images.githubusercontent.com/26900551/104443916-5afec200-5597-11eb-9dd3-1556cd7e8e82.png)

**Comment by LucasBrazi06** [comment]
@ClaudeROSSI how did you end-up with your email in the Stripe URL input field?
There is no default value here.

**Comment by Ninjeneer** [comment]
Indeed, there is no default value.
It seems like your browser indentified the combo [clear text field + password text field] as a login form, and autofilled it with your stored credentials.
We could eventually disable autofilling on those fields to avoid a such confusion for other users.

**Comment by ClaudeROSSI** [comment]
Right. It sounds like we simply need to set autocomplete="off" on all input fields to prevent this behavior.
I'll check it.

**Comment by ClaudeROSSI** [comment]
autocomplete="off" does not work (with Chrome). I tried it both on the form and on the input fields.
A lot of forums are discussing this issue ... 
I'm not yet familiar with "angular material" stuff ... I need to investigate a bit more to see if we can prevent those default values.

**Comment by ClaudeROSSI** [comment]
According to Mahdi the trick here is to simply put autocomplete="new-password" 
I'll do it at least on the private key input field.
