### ISSUE TITLE
06. Crypto - Migration task to change the crypto key in each tenant which is the same for history reason

### ISSUE THREAD

**Issue by stefania-santimbrean** [sap-labs-france/ev-server#2026]
- Repeating the [this issue](https://app.zenhub.com/workspaces/charge-angels-5dfcfa78b123df328c12f43d/issues/lucasbrazi06/ev-server/2024) for each tenant

**Comment by LucasBrazi06** [comment]
> * Repeating the step 3 for each tenant

Instead of "step 3", maybe a link to the issue when the step 3 is implemented would be nicer :)

**Comment by stefania-santimbrean** [comment]
Link added :)
