### ISSUE TITLE
Locking: Create exclusive lock with timeout

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-server#2031]
An exclusive lock should be requested with an optional timeout in ms.
When the lock cannot be acquired, a retry will be done until the timeout is reached.
If the blocking lock is released in the meantime, then the new one is set and the flow of the code can resume.

**Comment by LucasBrazi06** [comment]
First customer is smart charging @OliveGerste ;-)

**Comment by jerome-benoit** [comment]
What the difference with https://app.zenhub.com/workspaces/charge-angels-5dfcfa78b123df328c12f43d/issues/charge-angels/ev-dashboard/2285?

**Comment by LucasBrazi06** [comment]
This issue is to try to acquire a lock for a given period of time before it fails and the other is to delete a lock automatically after a given period of time.

**Comment by LucasBrazi06** [comment]
@jerome-benoit Would be nice to have unit tests.
Thanks.
