### ISSUE TITLE
04. Crypto - Backup scheduler job to monitor/finish the migration in case of crash

### ISSUE THREAD

**Issue by stefania-santimbrean** [sap-labs-france/ev-server#2044]
- Put a lock
  - Check migration
    - Cypher.migrate()
  - Release the lock

**Comment by LucasBrazi06** [comment]
Unit Test to move in issue #2024 + close this one.
Finally this is not a good idea to keep unit tests away from the issue #2024.
I need them to test and merge it in the end!
