### ISSUE TITLE
RESTful server: Implement also all public entries in addition to the ping one + Document it

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-server#2071]
Old REST :
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/de257dee-02fc-4340-af5e-b25629f2c8fc)

To add here:

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/8c93d82b-e66c-44ff-a5ef-352c7cb37a6c)

**Comment by LucasBrazi06** [comment]
@Ninjeneer Any news on this one?
Thanks!

**Comment by Ninjeneer** [comment]
Except for the ping one, every other endpoints will belong to their related entites router
So there is no really "public router"
