### ISSUE TITLE
Car Thumb images missing 

### ISSUE THREAD

**Issue by mahdibenromdhane** [sap-labs-france/ev-server#2084]
![image.png](https://images.zenhubusercontent.com/5e1f2e3de924e3a56bb760f1/000e8b44-9e4c-4da9-a73e-23b482453057)

**Comment by LucasBrazi06** [comment]
@mahdibenromdhane 
Just imported the prod DB and ran the migration tasks but still got empty thumbnails.

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/8264e43e-94fd-426c-af44-b855ff460e7a)

Could you check?

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane
> Just imported the prod DB and ran the migration tasks but still got empty thumbnails.
> 
> ![image.png](https://camo.githubusercontent.com/94458fe97babf22245302b918ea55bef2fa2191eb131a554028a7919f1249f29/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564666366386365663533383862646337393230303764662f38323634653433652d393466642d343236632d616634342d623835356666343630653761)
> 
> Could you check?

We need to trigger the sync car catalogs manually so we can apply this [PR](https://github.com/LucasBrazi06/ev-server/pull/2029) and run the migration task.
