### ISSUE TITLE
Security > Sensitive Data: Obfuscate HTTP body sensitive params in logs (POST) in addition to the existing ones

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-server#2091]
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/9a0c4302-bdc6-42be-bba7-fd61f248cdd2)

**Comment by roxiciobotea210** [comment]
Since I recently worked with sensitive data obfuscation (writing the tests) I have a remark on this one - client_id & client_secret are already part of the fields being obfuscated. Is there some other field to add?

**Comment by jerome-benoit** [comment]
You just have to ensure your tests cover that case. 
Once your PR will be merged, that issue will also be closed.

**Comment by roxiciobotea210** [comment]
> You just have to ensure your tests cover that case.
> Once your PR will be merged, that issue will also be closed.

Will add specific tests for both cases, thanks!
