### ISSUE TITLE
How to connect charger?

### ISSUE THREAD

**Issue by faisalm786** [sap-labs-france/ev-server#2099]
My settings are as follows

   "CentralSystems": [
    {
      "type": "ocpp",
      "implementation": "soap",
      "protocol": "http",
      "host": "localhost",
      "port": 8000,
      "debug": false
    },
    {
      "type": "ocpp",
      "implementation": "json",
      "protocol": "ws",
      "host": "localhost",
      "port": 9000,
      "keepaliveinterval": 30,
      "debug": false
    }
  ],

When I connect a charger at port 9000, with ws://localhost:9000/R77

it doesn't connect.

**Comment by LucasBrazi06** [comment]
Have you checked the logs?
Moreover a connection of a charger requires a token generated in the front-end for a given tenant (organization).

**Comment by faisalm786** [comment]
Hi I am not sure what the url should be to connect the charger and what port.

as far as I understood it was to connect to the backend ws://localhost:9000/[charger_address]

**Comment by faisalm786** [comment]
Is there anything I am missing? Please let me know. A little noobish here.

**Comment by LucasBrazi06** [comment]
> Hi I am not sure what the url should be to connect the charger and what port.
> 
> as far as I understood it was to connect to the backend ws://localhost:9000/[charger_address]

It's here:
![image](https://user-images.githubusercontent.com/25266945/108175998-b7f31800-7101-11eb-99c7-df0232d4882e.png)

**Comment by faisalm786** [comment]
I don't see ONBOARD NEW STATION in my local setup. How to enable it?

**Comment by LucasBrazi06** [comment]
> I don't see ONBOARD NEW STATION in my local setup. How to enable it?

What do you see? :)

**Comment by nkazbekov** [comment]
I have the same issue and tokens are not generated on onboard new station page:
![image](https://user-images.githubusercontent.com/4106437/112068716-b56a5f00-8b94-11eb-9592-85502d201484.png)
