### ISSUE TITLE
Enhance readme.md to include more setup info...

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-server#2121]
Got several feedback from external users.
It would be great to explain after the backend/front-end setup:
- [ ] The Tenant concept and how to access it in the Dashboard
- [ ] How to create a super admin user
- [ ] How to create a Tenant
- [ ] Validate the created Admin user in the created Tenant
- [ ] Log into the Tenant + Onboard new charging station (create Token)
Thanks!

**Comment by jerome-benoit** [comment]
+ Created a wiki page to guide new comers through the maze and give generic tips; 
+ Slightly amended the onboarding guide powerpoint and README.md
