### ISSUE TITLE
OCPI EMSP > chargeBoxSerialNumber: charging station not found because charging station filtered by id instead of chargeBoxSerialNumber

### ISSUE THREAD

**Issue by Jakob8** [sap-labs-france/ev-server#2124]
Hi Jakob,

As discussed, we have an issue in the current eMSP implementation.
The token will never be allowed by the eMSP tenant because we can’t retrieve the charging station.

We receive the following body when Gireve asks us to authorize a token
{
     "location_id": "37534",
     "evse_uids": [
             "121225"
     ]
}
Thanks to this data, we are able to build a unique id for the charge point (location_id + ‘-‘ + evse_uids). 
This identifier is mapped to the chargeBoxSerialNumber, not to the charging station id. 

 

So, you have to update the code to retrieve a charging station by chargeBoxSerialNumber, not by id.

 

https://github.com/Charge-Angels/ev-server/blob/6bb38b43d9192b057a7ecf541fb05d42c096eaff/src/server/ocpi/ocpi-services-impl/ocpi-2.1.1/EMSPTokensEndpoint.ts#L122

Be careful, the buildChargingStationId method is used several times. You may have to update this code also.

 

Hope this helps,
Sébastien

**Comment by LucasBrazi06** [comment]
> So, you have to update the code to retrieve a charging station by chargeBoxSerialNumber, not by id.

We have a structure in Charging Station where we store OCPI data and evse_id in it.
Why using the serial number?
