### ISSUE TITLE
Charging Station > Meter Values: Chart is wrong when sampling is 10 secs

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-server#2125]
When increased to 30s result is correct (at the end of the chart).
Bug reported by Gerald:
![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/dea2b76e-40de-4d15-81a6-551f122ae612)

**Comment by jerome-benoit** [comment]
The reproducibility pattern is required: 
+ charging station dependent? 
+ other interval tested?   

With ev-simulator and MeterValueSampleInterval set to 5s or 10s that does not occur so it's very likely to be a timestamping issue charging station side.

**Comment by LucasBrazi06** [comment]
@jerome-benoit Talk to Gerald.
Thanks.

**Comment by jerome-benoit** [comment]
@cybergege: I need more informations on the issue.
