### ISSUE TITLE
Bug: Basic user can't update his plateID

### ISSUE THREAD

**Issue by mahdibenromdhane** [sap-labs-france/ev-server#2134]
As discussed in [this](https://github.com/Charge-Angels/ev-dashboard/issues/2000#issuecomment-785089813) issue. 

Basic user should be able to update his plateID.

**Comment by LucasBrazi06** [comment]
That's normal :)

**Comment by mahdibenromdhane** [comment]
> That's normal :)

I'v miss wrote the title,
 Basic user should be able to update his plateID.
