### ISSUE TITLE
Eichrecht : Signed Data is not correctly transmited with some systems

### ISSUE THREAD

**Issue by WillyLellouch** [sap-labs-france/ev-server#2242]
Signed Data is only taken from MeterData where it should be taken from StopTransaction as well.

**Comment by jerome-benoit** [comment]
@WillyLellouch could you please give us the full technical details on the issue or make a draft PR from your fix branch for initial reviewal and consider that issue as a top priority? 

Thanks.

**Comment by WillyLellouch** [comment]
@jerome-benoit draft PR coming tommorow at the latest

**Comment by jerome-benoit** [comment]
> @jerome-benoit draft PR coming tomorrow at the latest

@WillyLellouch We are tomorrow since yesterday. Could you please give us a status?

**Comment by WillyLellouch** [comment]
@jerome-benoit I was a bit too optimistic with the timing. I've encountered a bug in my implementation that I'm resolving today. Also, should I include my unit tests in the PR or make a separate one ?

**Comment by jerome-benoit** [comment]
You can put everything in the same PR. Thanks.

**Comment by jerome-benoit** [comment]
@WillyLellouch: 5 more days since without any status update on a customer critical issue. What the hell is happening?

**Comment by WillyLellouch** [comment]
@jerome-benoit Sorry for the lack of communication. I've finished to implement my solution but I have some trouble with the unit tests.
As in I can't run them and I don't know why that is.
The solution I implemented is the simplest I could do. the reason it took longer than expected is that I originally went in a completely different direction that required me to rewrite large sections of code and I got lost in the weeds. My new code only changes 1 file.
Since I could not do the Unit tests properly, I'll do the PR anyway and you can see if this is satisfactory. Who must I ask for indications as to why my Unit Tests are not operative ?

**Comment by jerome-benoit** [comment]
The checks at PRs do a unit tests run.

For developers support, we  have a teams and a mailing list to ask for it.

Thanks.

**Comment by WillyLellouch** [comment]
The fix is non functional with ChargeX.
I'm investigating to see what went wrong in testing

**Comment by WillyLellouch** [comment]
@LucasBrazi06 The tests were a success. There were no additional issues to report

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 The tests were a success. There were no additional issues to report

Ok, perfect!
Thanks!
