### ISSUE TITLE
Non-admin users can read every charging stations

### ISSUE THREAD

**Issue by Ninjeneer** [sap-labs-france/ev-server#2279]
Non-admin users should only be able to read charging stations of assigned sites 
![image.png](https://images.zenhubusercontent.com/5dfd46a3563ec65759521f2d/2f8793a3-626b-4c1d-b9c5-72e4172da539)

But can actually read charging stations of any sites.

**Comment by LucasBrazi06** [comment]
I just checked and it is working.
Could you give me more info?
Thanks.

**Comment by Ninjeneer** [comment]
Abdul from ChargeX reported the issue, and I was able to reproduce it on my side.
I created a basic user on my local slf, only assigned to Mougins. I am able to read charging stations from Caen, triggering the /api/chargingstations/the_chargingstation_id

Also, it seems that there are no site checks on the handleGetChargingStation method.

**Comment by LucasBrazi06** [comment]
Ah ok, because the list of charging stations is correct on my local machine.
@roxiciobotea210 Could you have a look at this issue?
Thanks

**Comment by roxiciobotea210** [comment]
Hi,
I am not able to reproduce the issue yet. Just a question to you @LucasBrazi06 - when refactoring authorization for Company/Site/SiteArea was I supposed to NOT modify the `AuthorizationsDefinition.ts` file? Because I did (removed some of the custom filtering) and I'm thinking that could be causing this issue?

**Comment by LucasBrazi06** [comment]
> Hi,
> I am not able to reproduce the issue yet. Just a question to you @LucasBrazi06 - when refactoring authorization for Company/Site/SiteArea was I supposed to NOT modify the `AuthorizationsDefinition.ts` file? Because I did (removed some of the custom filtering) and I'm thinking that could be causing this issue?
> 
> Edit - However I did not remove anything from the ChargingStations...
> 
> Edit 2 - I checked, it's not because of that. I will implement the check.

Then it's a bug not visible in the UI as the list is correctly filtered.
Thanks for the fix.
