### ISSUE TITLE
Org Unit Tests - Fails when run a second time

### ISSUE THREAD

**Issue by roxiciobotea210** [sap-labs-france/ev-server#2290]

**Comment by LucasBrazi06** [comment]
I made a change also in Site service to align it with the rest and got 2 unit tests failing which is related to this issue I think:

![image](https://user-images.githubusercontent.com/25266945/114042069-622b2880-9885-11eb-91d0-205f6c1787df.png)

For the first one, it should have failed fail on the canUpdate() is the SiteService but the user which is used here is a Site Admin with the right to update the Site, so that's normal that we don't get 403 error.
We should have had a real Basic user for that unit test.

User tested is Site Admin here:
```
{
 "id": "5ce249a1a39ae1c056c123ab",
 "role": "B",
 "name": "KOCH",
 "mobile": null,
 "email": "basic-serge.fabiano@sap.com",
 "tagIDs": [
  "A12342"
 ],
 "firstName": "Paris",
 "locale": "en_US",
 "language": "en",
 "currency": null,
 "tenantID": "aaaaaaaaaaaaaaaaaaaaaaa3",
 "tenantName": "utorg",
 "tenantSubdomain": "utorg",
 "userHashID": "492fc2a6b3048d4c0449ddd938a9f6e8b2e9ffe9da20b9017f8bb3b996c59087",
 "tenantHashID": "128a2ac1997d3ae7d2f5a7e9bcc391692f2dcfa94488691571b6ad45435f84e7",
 "scopes": [
  ...
  "Site:Read",
  "Site:Update",
  "Sites:List",
  ...
 ],
 "sitesAdmin": [
  "606f0e8d93558ee5841d3efe"
 ],
 "sitesOwner": [
  "606f0e8d93558ee5841d3f19"
 ],
 "sites": [
  "606f0674130f31dde7854b9c",
  "606f0e8d93558ee5841d3f19",
  "606f0e8d93558ee5841d3ee2",
  "606f0e8d93558ee5841d3efe",
  "5ce249a2372f0b1c8caf9294",
  "5ce249a2372f0b1c8caf6532",
  "5ce249a2372f0b1c8caf8367"
 ],
 "activeComponents": [
  "organization"
 ],
 "iat": 1617890957,
 "exp": 1617934157,
}
```

You can also check the second one.

Thanks!

**Comment by roxiciobotea210** [comment]
This happens on master-qa branch?

**Comment by roxiciobotea210** [comment]
Managed to reproduce them, will find a fix, do not merge the branch please. :)

**Comment by roxiciobotea210** [comment]
I investigated the issue and I am not so sure the test is the problem.

As you see in the screenshot below, the user is not admin for the site that is used for update, yet the update returns 200.
I also tested in Postman - created a new site, assigned a basic user to the site, logged in with the basic user & tried to update the site - it worked.

![Screenshot 2021-04-08 at 19.10.19.png](https://images.zenhubusercontent.com/600fe9b1a2c5e21f380396f7/0e687534-e432-4155-b0bc-ca45c5e98949)

Are there any 'siteAdmin' checks in the code?

**Comment by LucasBrazi06** [comment]
> As you see in the screenshot below, the user is not admin for the site that is used for update, yet the update returns 200.
> I also tested in Postman - created a new site, assigned a basic user to the site, logged in with the basic user & tried to update the site - it worked.

Thanks a lot for the info!
A Site Admin user is just a user with role Basic which was marked Site Admin in the DB for certain sites thus the dynamic checks.

What I don't get is that the pure Basic user should not be able to update a site and pass the static check below in SiteService class:

```
    // Check auth
    if (!Authorizations.canUpdateSite(req.user)) {
      throw new AppAuthError({
        errorCode: HTTPAuthError.FORBIDDEN,
        user: req.user,
        action: Action.UPDATE, entity: Entity.SITE,
        module: MODULE_NAME, method: 'handleUpdateSite',
        value: filteredRequest.id
      });
    }

```

Basic user has only READ/LIST auth:

![image](https://user-images.githubusercontent.com/25266945/114087478-3a06ee00-98b4-11eb-8dc2-01290cb10f00.png)

There must be a bug somewhere :-)

**Comment by roxiciobotea210** [comment]
From what I understood by running the app with debugger and going through the flow step by step, if a user is siteAdmin for **any** site, the "siteAdmin" group is added to the user in `getAuthGroupsFromUser`. And then this is also taken into account:

<img width="805" alt="Screenshot 2021-04-09 at 10 34 40" src="https://user-images.githubusercontent.com/78014067/114145932-a408ad00-991f-11eb-8647-47129a28d3a2.png">

Looks like this is why the user is able to update? 
This line in siteAdmin authorization description used to have a condition, which I removed when refactoring because I got rid of the ID in the static check:

<img width="527" alt="Screenshot 2021-04-09 at 10 39 57" src="https://user-images.githubusercontent.com/78014067/114146217-ffd33600-991f-11eb-9c41-131ca391b7eb.png">

**Comment by LucasBrazi06** [comment]
> Looks like this is why the user is able to update?
> This line in siteAdmin authorization description used to have a condition, which I removed when refactoring because I got rid of the ID in the static check:

Yes, this is how it works (you got it ;-)).
Then in the Unit Test or when you test with a pure Basic user (not Site Admin) you should not be able to update a Site.
If this is true then the user used in the unit test is wrong (check my first comment ;-))

**Comment by roxiciobotea210** [comment]
> Yes, this is how it works (you got it ;-)).
> Then in the Unit Test or when you test with a pure Basic user (not Site Admin) you should not be able to update a Site.
> If this is true then the user used in the unit test is wrong (check my first comment ;-))

OK, I think I understand what you mean now & will change the test. :) 
But what if the user is assigned to 2 sites & he is SiteAdmin only for one of them? Shouldn't he be able to update only the site for which he is SiteAdmin? (This is the part I'm still confused about.)

**Comment by LucasBrazi06** [comment]
> But what if the user is assigned to 2 sites & he is SiteAdmin only for one of them? Shouldn't he be able to update only the site for which he is SiteAdmin? (This is the part I'm still confused about.)

Yes, this is exactly how it should work.
In that case the 'authorized' flag should return 'false' and the exception should be thrown:

![image](https://user-images.githubusercontent.com/25266945/114151746-bb469b00-991d-11eb-9cd7-9d64f73df794.png)

**Comment by roxiciobotea210** [comment]
All tests are ok now, [this](https://github.com/sap-labs-france/ev-server/pull/2291/commits/930cc18a455e6a49dacdae7819afbb005847bd9a) is the change I added for the Sites, please check if it's ok.

**Comment by LucasBrazi06** [comment]
> All tests are ok now, [this](https://github.com/sap-labs-france/ev-server/pull/2291/commits/930cc18a455e6a49dacdae7819afbb005847bd9a) is the change I added for the Sites, please check if it's ok.

Thanks a lot Roxana!
I'll have a look.

**Comment by LucasBrazi06** [comment]
@roxiciobotea210 After running the Org unit tests, the Registration token tests fails.
Could you please check?
Thanks
