### ISSUE TITLE
Reset firmware update status to "Installed" at receiving successful boot notification 

### ISSUE THREAD

**Issue by jerome-benoit** [sap-labs-france/ev-server#2305]

**Comment by jerome-benoit** [comment]
The issue here is that the status is expected be sent after the charging station reboot to the new firmware version in the OCPP spec.

**Comment by LucasBrazi06** [comment]
> The issue here is that the status is expected be sent after the charging station reboot to the new firmware version in the OCPP spec.

In other words, that's a bug on their side right?

**Comment by jerome-benoit** [comment]
> > The issue here is that the status is expected be sent after the charging station reboot to the new firmware version in the OCPP spec.
> 
> In other words, that's a bug on their side right?

In any case that issue is meant to workaround bugs in the firmware installation status sent by charging station. 

But I can't add that workaround at boot notification: the firmware installation status with status "Installed" must be sent after the reboot, so after the boot notification sending and acceptation. 

It can be a scheduler task checking the firmware installation status, the charging station online status doing reset once a day.
