### ISSUE TITLE
Import Tags: Importing a CSV file under Windows OS in Chrome fails with invalid file format

### ISSUE THREAD

**Issue by LucasBrazi06** [sap-labs-france/ev-server#2326]
Take whatever CSV file and import it in Chrome on a Windows OS (you can use a VM):

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/ca875078-1376-49f0-9a29-5a1ded1064ac)

In logs we have the following message:

![image.png](https://images.zenhubusercontent.com/5dfcf8cef5388bdc792007df/68b0e376-ed69-4138-9335-3ba707ce4555)

**Comment by LucasBrazi06** [comment]
@cabch Customer issue, to be fixed asap 😊

**Comment by cabch** [comment]
waiting for VM to be created to test fix
