### ISSUE TITLE
Authorization bug

### ISSUE THREAD

**Issue by roxiciobotea210** [sap-labs-france/ev-server#2459]
admin that are also site admin or owner can't see everything in the organisation tree

**Comment by LucasBrazi06** [comment]
Report PR comments:

> The problem is that extra filters added in case the user is siteOwner or siteAdmin overlap with the fact that an admin can do anything. For now I can add a check that prevents dynamic filters from being applied in case the user is an admin. But the issue will need to be revisited when Serge is back to see what is the elegant way to address it. (I think that after all the entities will be updated to the new auth concept, it won't be an issue anymore, but I need to check with Serge.)
