### ISSUE TITLE
Smart Charging > Ensure safety, fix known issues 

### ISSUE THREAD

**Issue by OliveGerste** [sap-labs-france/ev-server#2479]
- [ ] Implement backup mechanism if smart charging fails, e.g. because of unreleased locks
- [x] Implement lock timeout
- [x] Fix asset backup calculation bug
- [x] Apply profiles with low limits first to ensure that there are no transition periods with high limit, where the corresponding low limit is not applied yet
- [x] Check if the charging profile, which is in place differs from the new one before applying to the cs
- [x] Fix settings check, before calling the optimizer
- [x] Set timestamp arrival times and current time to 0 (get profiles for the next 24h --> needed for overnight price optimization)
- [x] Reduce only one phase of the root fuse, when single phased station is excluded from smart charging on three phased site area
- [x] When excluding dc stations, take into account efficiency of station
- [x] Charging Stations without charge point cause an error (Can happen when the charging station is not excluded from smart charging)
- [x] If there is a problem with an active transaction (which is not existing) smart charging fails for the site area
- [ ] Unit tests to be added -> Car Management, Efficiency

**Comment by jerome-benoit** [comment]
For the locking, you have to extend the current primitive with an acquire timeout and add a release time deadline.

**Comment by OliveGerste** [comment]
> For the locking, you have to extend the current primitive with an acquire timeout and add a release time deadline.

I think there is already an issue for this right? https://github.com/sap-labs-france/ev-dashboard/issues/2285

The aim of the first point is to have a backup mechanism in general if smart charging fails for whatever reason.

**Comment by jerome-benoit** [comment]
The backup mechanism must rely on that locking primitive. It's the easiest way to have it.

**Comment by OliveGerste** [comment]
> The backup mechanism must rely on that locking primitive. It's the easiest way to have it.

The backup mechanism I have in mind would apply secure TxDefaultProfiles to each station, when smart charging is activated for a site area.
Then the algorithm can apply TxProfiles, which are used for the transactions and are able to charge more.
If smart charging fails (Maybe for another reason than locking also), it will charge the default value and we are save.

Nevertheless the locking issue needs to be solved you are right.

**Comment by OliveGerste** [comment]
@jerome-benoit 
To solve the locking issue. What would be the approach. 
Do we create a scheduled task which checks if the locks are timed out.
Or do we add this functionality to the acquire methodology and if an new lock is needed to we check the old one in place is still valid? And if not releasing it.

**Comment by jerome-benoit** [comment]
@OliveGerste: I propose that we do a meeting next week with @LucasBrazi06 to discuss it, along with your proposal for posting asset consumptions.

**Comment by LucasBrazi06** [comment]
> @jerome-benoit
> To solve the locking issue. What would be the approach.
> Do we create a scheduled task which checks if the locks are timed out?
> Or do we add this functionality to the acquire methodology and if an new lock is needed, we check the old one in place is still valid? And if not releasing it.

Both techniques :-)
Let's discuss it during your meeting.

**Comment by OliveGerste** [comment]
@LucasBrazi06 Applying the calculated charging profiles to all stations very frequently takes a lot of time. 
What do you think about checking if the charging profile changed, before we apply it again. (We already retrieve the existing ones from the database)
And we only apply it, when the profile schedule and the start changed.

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 Applying the calculated charging profiles to all stations very frequently takes a lot of time.
> What do you think about checking if the charging profile changed, before we apply it again. (We already retrieve the existing ones from the database)
> And we only apply it, when the profile schedule and the start changed.

Very good idea :-) 👍  !!!
