### ISSUE TITLE
Billing - Pricing - STRIPE - Rounding energy consumption

### ISSUE THREAD

**Issue by ClaudeROSSI** [sap-labs-france/ev-server#2486]
The way the transaction amount is truncated at the PRICING level has a siffe effect on the energy consumption shown on the invoices.

Proposal: Apply the same rounding logic to both the amount and the energy consumption.

![image.png](https://images.zenhubusercontent.com/5fa82ce7552e0aed8eb43377/1d3a1fa1-531d-4490-973e-8f47f466737d)

**Comment by ClaudeROSSI** [comment]
Shall I ignore the rounded price that the pricing provides?

![image](https://user-images.githubusercontent.com/26900551/119951002-c7ed8400-bf9b-11eb-8e6e-e52e10e14e23.png)

**Comment by ClaudeROSSI** [comment]
Ok. 

I'll change the invoice line item just to show the real consumption.
This should be less confusing.

![image](https://user-images.githubusercontent.com/26900551/119968970-4c490280-bfae-11eb-9bfd-038017c50118.png)

**Comment by LucasBrazi06** [comment]
You can also create a similar property for rounding the consumption like the pricing (migration task).
