### ISSUE TITLE
billing - session history - show invoice status

### ISSUE THREAD

**Issue by ClaudeROSSI** [sap-labs-france/ev-server#2494]
The session history was supposed to show (for each session) the corresponding invoice number. This can be easily implemented when the 'immediate billing' option is ON. However, when the 'periodic billing' is selected, the invoice number is not known until the end of the month. It therefore makes it difficult to maintain that information in each session row.

![image.png](https://images.zenhubusercontent.com/5fa82ce7552e0aed8eb43377/2f7be9aa-d3ca-4b57-a919-da2a32f3e6c5)

**Proposal**: 
Knowing that we may have a single invoice for several sessions. It would make sense to only show the billing status instead of the invoice number. 

Billing status could be: not billed, draft, billed, error or pending
- **PENDING** will appear only when the billing process is ongoing (i.e.: when an async task is about to run and change the status)
- '**draft**' denotes the fact that the billing will be completed at the end of the month - only then the invoice number will be known.
- '**not billed**' - The billing of charging session is not yet activated

The fact that we only show the status will improve the performance as well (for both the session history tab and the session in error tab). Because the information can be fetched easily and we do not need to replicate too much data (from the invoice to the session collection).

**Comment by LucasBrazi06** [comment]
After the first transaction, we should create a billing item and an invoice that we keep as open right?
Why don't we have an invoice number here then?

Nevertheless, we can keep the invoice number empty, it not a problem for me.
The status of the invoice is displayed in the invoice list, no need to repeat it for each session in the history.

**Comment by ClaudeROSSI** [comment]
> After the first transaction, we should create a billing item and an invoice that we keep as open right?
> Why don't we have an invoice number here then?
> 
> Nevertheless, we can keep the invoice number empty, it not a problem for me.
> The status of the invoice is displayed in the invoice list, no need to repeat it for each session in the history.

After the first transaction the invoice is not 'open' ... it remains in a 'draft' state. This is why we do not know the invoice number. For some legal constraints (to avoid gaps in the invoice number sequence), the final invoice number is generated only when finalising the invoice (at the end of the month). 

From an end-user perspective, I think showing the status is sufficient and clear enough.

**Comment by LucasBrazi06** [comment]
This does not shock me to keep only the invoice ID.
We can keep the Invoice ID with a jump to the invoice list: when not present, transaction is not billed.
We need an Invoice ID filter.

**Comment by ClaudeROSSI** [comment]
> This does not shock me to keep only the invoice ID.
> We can keep the Invoice ID with a jump to the invoice list: when not present, transaction is not billed.
> We need an Invoice ID filter.

ok. But when you say ID you are talking about our invoice ID. Right? not the invoice number!?!
Do we really want to show our internal ID to the end user?

**Comment by LucasBrazi06** [comment]
> ok. But when you say ID you are talking about our invoice ID. Right? not the invoice number!?!
> Do we really want to show our internal ID to the end user?

No the real invoice ID not our internal one.

**Comment by ClaudeROSSI** [comment]
well ... i'm confused ;)

we have: 
- Invoice ID
- Stripe Invoice ID
- Stripe Invoice Number

We also have:
- Stripe Invoice Item ID

I would expect that the end-user only see the legal stuff: the invoice number.
But then we only have it at the end of the month.

**Comment by LucasBrazi06** [comment]
Perfect with the invoice number.
Then it's empty until we have the invoice at the end of the month.
I'm ok with that except if you see any other issues?

**Comment by ClaudeROSSI** [comment]
> Perfect with the invoice number.
> Then it's empty until we have the invoice at the end of the month.
> I'm ok with that except if you see any other issues?

ok.  Perfect.
Then I have to fix a bug. Because right now we do not see it event when 'Immediate billing' is on!

**Comment by LucasBrazi06** [comment]
> we have:
> 
> * Invoice ID
> * Stripe Invoice ID
> * Stripe Invoice Number
> 
> We also have:
> 
> * Stripe Invoice Item ID

Btw, I don't want any 'stripe' naming in the properties :-)

**Comment by ClaudeROSSI** [comment]
Well .. to be able to display the invoice Number (and not the invoice ID( I had to fix both the backend and the frontend side.
Thanks for reviewing!
