### ISSUE TITLE
Assets > provide an API Endpoint for pushing Asset consumptions

### ISSUE THREAD

**Issue by OliveGerste** [sap-labs-france/ev-server#2570]

**Comment by OliveGerste** [comment]
@LucasBrazi06 
Just to be sure. I would introduce the new Routing Framework and Validation for assets with this issue. 
So the AssetRouter and AssetValidator would be implemented containing the new endpoint.

**Comment by LucasBrazi06** [comment]
@OliveGerste Yes, exactly!
If you need help, @Ninjeneer can help you :-)
