### ISSUE TITLE
billing - UI - Delete test data button

### ISSUE THREAD

**Issue by ClaudeROSSI** [sap-labs-france/ev-server#2591]
BE: Provide the information to the dashboard to enable the "Delete test data" button

FE: enable the "test data deletion" only when targeting a test account

**Comment by LucasBrazi06** [comment]
@ClaudeROSSI PR still in Requested Change on purpose?

**Comment by ClaudeROSSI** [comment]
Closing this one - changes have been made differently with another PR.

**Comment by ClaudeROSSI** [comment]
Closing this one - changes have been made differently with another PR.
