### ISSUE TITLE
Tenant logo in mail notifications is not displayed on QA

### ISSUE THREAD

**Issue by jerome-benoit** [sap-labs-france/ev-server#2599]
Could you please check if that's not related to the REST endpoints migration?

**Comment by Ninjeneer** [comment]
This endpoint has not been migrated yet. There is only a schema validator, which seems to work well (tested in local + should return a 500 error if it fails, but it's not)
It seems to come from elsewhere

**Comment by LucasBrazi06** [comment]
It works on my side
