### ISSUE TITLE
Admin without tag cannot stop any transaction

### ISSUE THREAD

**Issue by Ninjeneer** [sap-labs-france/ev-server#2641]
Admin without any tag (or haven't logged off/in after new tag assignment) cannot stop any transaction

Reproduction steps :

- Log as a random user and start a remote transaction
- Log as an admin without any tags and try to stop the transaction

![image.png](https://images.zenhubusercontent.com/5dfd46a3563ec65759521f2d/0d4efd95-15de-4f10-bcba-9b040f3e506f)

The tags of the user sending the stop command are checked, while it should not be for admins
![image.png](https://images.zenhubusercontent.com/5dfd46a3563ec65759521f2d/55260c20-17ce-48bc-a0e9-62169a597ff5)

**Comment by hughsheehy** [comment]
When was this completed? I'm having this error today. 

The logs say 

User API > OCPP Command 'RemoteStopTransaction' has failed: The user does not have any active badge

**Comment by hughsheehy** [comment]
I got the pPUT API to work, but I had to add the tagID and visualTagID into the args payload.
