### ISSUE TITLE
EV station not connecting | Error : Web Socket Protocol is mandatory

### ISSUE THREAD

**Issue by rccess** [sap-labs-france/ev-server#2761]
Hello community,

i am trying to onboarding new ev station through OCPP 1.6 J

The url parameter like this 

ws://ev.texxxxxxob.cloud:8010/OCPP16/611e3xxxx61c75f3f11752d/612f2exxxxx1db1fa623c259

But not connecting getting error the following,

![image](https://user-images.githubusercontent.com/32220165/131643860-31b889a2-d414-4080-af5f-1c73717a460a.png)

I need to know, is there any bug in code or i am missing someting to call ?

Please do advise

Thanks

**Comment by LucasBrazi06** [comment]
Your charging station, when opening a WS, should provide the 'protocol' property equals to 'ocpp1.6'.

**Comment by LucasBrazi06** [comment]
Closed due to inactivity
