### ISSUE TITLE
Car Connector - Integrate Tronity API to retrieve SOC

### ISSUE THREAD

**Issue by OliveGerste** [sap-labs-france/ev-server#2832]

**Comment by LucasBrazi06** [comment]
No need to put the Asana link here, it's internal.
But the link of this issue in Asana yes ;-)

**Comment by OliveGerste** [comment]
> No need to put the Asana link here, it's internal.
> But the link of this issue in Asana yes ;-)

Okay, so it is the other way around. I will change it. Thanks.
