### ISSUE TITLE
SSL error:0909006C:PEM routines:get_name:no start line

### ISSUE THREAD

**Issue by DhananjaySoni** [sap-labs-france/ev-server#2972]
in the config.js file

1. what file format in sslKey, sslCert is required at all the 4 places. where can these files be accessed/what exactly are these files?

2. what path are we supposed to give there? is it inside src/assets we need to create ssl folder? or something else? for eg:- "ssl/private.key"

**Comment by DhananjaySoni** [comment]
I am hosting the server with https. For that, ssl key and certificate are needed. There are fields in config.json (https) for these files but I don't understand which file formats are to be added there. I have .key, .crt files as well as .pem files for the key and certificate.
I tried all these files but it gives the same error always ( error:0909006C:PEM routines:get_name:no start line
) . Even if I don't provide the files, I get this same error. 
So I wanted to know where to keep these files, how to provide their addresses in config.json and which file formats to use

**Comment by sharpe1907** [comment]
Hi DhananjaySoni,

How could you solve this problem ? Could you please tell me the solution ?

thanks..
