### ISSUE TITLE
Option to create car model manually in CAR CATALOGS

### ISSUE THREAD

**Issue by rccess** [sap-labs-france/ev-server#2998]
there is only option to add car is ev-database.org  but there are few cars which models not updated on ev-database.org

want to add the Option to create car model manually in CAR CATALOGS

thanks

**Comment by rccess** [comment]
any chance to look into this issue ?

i tried to recover files from old version and car got updated once from file car-definition.json, but on modification (remove one car & added another car) of car-definition.json, not updating again and no option to delete cars from dashboard interface, can you help you please 


thanks

**Comment by LucasBrazi06** [comment]
@rccess Let @mahdibenromdhane deliver the proper fix ;-)

**Comment by rccess** [comment]
can you please help me to get it fix

**Comment by LucasBrazi06** [comment]
It's holiday period at the moment.
The fix will be deployed soon

**Comment by rccess** [comment]
@LucasBrazi06 Can you please help to fix this bugs (which was due to deleted files by mistake from your side)

**Comment by LucasBrazi06** [comment]
This fix should be deployed this week.

**Comment by rccess** [comment]
Thanks for your update ! hope to see this to fix in this week

**Comment by LucasBrazi06** [comment]
@mahdibenromdhane Any news on this one?

**Comment by mahdibenromdhane** [comment]
> @mahdibenromdhane Any news on this one?

@LucasBrazi06 I will push the fix by tomorrow.

**Comment by LucasBrazi06** [comment]
Email quote in FR

```
Voila les changements que j’aimerai :

- Le fichier Json qui contient les cars ne doit pas suivre le format ev-database mais notre type (CarCatalog)
  - Tu check avec un schema Json
  - Tu importes direct dans la DB
 
- Les images doivent etre correctement sizées et importées directement dans la DB
  - Tu dois avoir une image thumb et les autres ont toutes la meme taille/format
  - Tu importes tel quel dans la DB
```

**Comment by LucasBrazi06** [comment]
@mahdibenromdhane Requested changes to implement
