### ISSUE TITLE
Invoices are not generating for payment

### ISSUE THREAD

**Issue by rccess** [sap-labs-france/ev-server#3013]
Hello team,

We added stripe , when new user getting signup , profile creating on stripe 

![image](https://user-images.githubusercontent.com/32220165/139514881-58766e4d-afe2-47f3-a81a-68ba9ace8d3f.png)

![image](https://user-images.githubusercontent.com/32220165/139514759-be7f369d-6670-4564-9571-c5eb1be25aa8.png)

what may be the reasons

below is the defined in config file for schedule task

![image](https://user-images.githubusercontent.com/32220165/139514825-5a1d34aa-af84-4d50-9cd1-306ce1232220.png)

**Comment by LucasBrazi06** [comment]
@ClaudeROSSI Could you check?
Thanks!

**Comment by ClaudeROSSI** [comment]
Hello,

@rccess : Can you provide more details about the stripe configuration?
On which tenant are you facing the problem?

Regards,
Claude

**Comment by rccess** [comment]
invoice are not generating for any of the tenant and user 

![image](https://user-images.githubusercontent.com/32220165/139574161-287673b8-c645-43e3-8e60-f30585b9b06d.png)

**Comment by ClaudeROSSI** [comment]
I'm afraid, the information provided is not sufficient. Which customer accounts (which tenant) are you talking about.
Please send me the URL where to logon! I'll then register myself and ask you to grant me the admin role. Only then I'll be able to investigate.

Claude

**Comment by rccess** [comment]
okay

**Comment by rccess** [comment]
@ClaudeROSSI  i have activated your account and changed the permission to admin

**Comment by ClaudeROSSI** [comment]
Thanks. I now have access to the logs.

At a first glance it seems that the currency set in the "> integration settings > pricing module" does not match the one set in your stripe account. Can you please double check? We need the same currency on both sides!

Please also confirm that a few customers have been created on the STRIPE side. 
Be aware that STRIPE customers are created on-demand (i.e.: each time a user enters a payment method). So you should see there only the ones that have been able to enter their credit card information.

Let me know if you need more information.
Thanks,
Claude

**Comment by ClaudeROSSI** [comment]
Please also make sure you are properly connected to the STRIPE productive account. One common mistake is to have eMobility pointing to the strip test account (i.e.: by entering a wrong secret key in the BILLING settings).
Best regards,
Claude

**Comment by rccess** [comment]
thanks for the update

i do have INR in Stripe account (it is in production mode) as well updated same in dashboard

![image](https://user-images.githubusercontent.com/32220165/139638510-0c431281-50e1-42c4-8b5a-e524288d34d8.png)

but invoice is generating yet

![image](https://user-images.githubusercontent.com/32220165/139639239-089d9e39-8131-4e60-9741-c71a412e8bba.png)


![image](https://user-images.githubusercontent.com/32220165/139639190-3650b442-968f-40fb-9802-18ee26454e90.png)

you can check last charging session

thanks

**Comment by ClaudeROSSI** [comment]
Hello,

All sessions have been made on a pubic site. No invoices are generated when the site is public.
Please make sure to uncheck that option to actite the billing module!

<img width="1116" alt="2021-11-03_08-15-46" src="https://user-images.githubusercontent.com/26900551/140021546-cec60af9-ca44-4fee-ba01-666471435b0f.png">

Le me know if you have any concerns!

**Comment by rccess** [comment]
thanks for your update

i have updated the sites without public 

![image](https://user-images.githubusercontent.com/32220165/140063485-8c7b413f-a0bb-4272-9494-ce2b46f5369b.png)

and started 2 sessions but still no invoice generated yet

![image](https://user-images.githubusercontent.com/32220165/140063632-02eaaa49-d4e5-4e2e-8c5d-1fb0f23b4c65.png)

**Comment by ClaudeROSSI** [comment]
I have a question regarding the scheduled tasks.
Why did you change the settings for the task: **SynchronizeBillingInvoicesTask**

This task is deprecated. Please switch it OFF like in the example below:



      {
        "name": "SynchronizeBillingUsersTask",
        "active": true,
        "periodicity": "0 0 * * *",
        "config": {}
      },
      {
        "name": "BillingPeriodicOperationTask",
        "active": true,
        "periodicity": "0 3 * * *",
        "config": {}
      },
      {
        "name": "SynchronizeBillingInvoicesTask",
        "active": false,
        "periodicity": "0 0 * * *",
        "config": {}
      },

**Comment by rccess** [comment]
i have changed the config.json as suggested 

![image](https://user-images.githubusercontent.com/32220165/140090312-93943ca7-acbd-4a35-8a03-4557ffaacb20.png)


still not generating invoice for long session as well !

![image](https://user-images.githubusercontent.com/32220165/140090160-bd578b1f-99c2-4f5a-acfa-7ac809144c9c.png)

**Comment by rccess** [comment]
issued fixed 

"AsyncTask": {
    "active": true,
    "nbrTasksInParallel": 4
  },

it was false in config file


thanks for your help
