### ISSUE TITLE
mobile app scanning to add tenant is not working

### ISSUE THREAD

**Issue by rccess** [sap-labs-france/ev-server#3019]
Hello team,

mobile app scanning to add tenant is not working

Showing Error Unknown Cloud 'AWS'

![image](https://user-images.githubusercontent.com/32220165/140004167-4e382bfd-970e-4f17-8956-89585c72cf05.png)

below is the configuration 

![image](https://user-images.githubusercontent.com/32220165/140004127-9117a98f-1e47-4b13-b1e7-341f489c6593.png)

**Comment by LucasBrazi06** [comment]
@AlixH Could you check?

**Comment by AlixH** [comment]
The configuration shoud be as follow : 
```
public static readonly DEFAULT_ENDPOINT_CLOUD_ID = 'aws';
  public static readonly ENDPOINT_CLOUDS: EndpointCloud[] = [
    { id: Configuration.DEFAULT_ENDPOINT_CLOUD_ID, name: 'Amazon Web Service', endpoint: Configuration.AWS_REST_ENDPOINT_PROD }
  ];
```

The error is shown because the DEFAULT_ENDPOINT_CLOUD_ID is 'app' but should be 'aws'  (encoded in the QR-Code)

**Comment by LucasBrazi06** [comment]
Closed for inactivity.
Let me know if you still have the issue.
Thanks!
