### ISSUE TITLE
Mail not receiving properly 

### ISSUE THREAD

**Issue by rccess** [sap-labs-france/ev-server#3034]
Hello team,

On simulation of Charging stations mails received to admin is not in proper conditions. Please look into once below

![image](https://user-images.githubusercontent.com/32220165/140605956-c2889e54-dbc5-4fcb-9ab6-17a5fdb5cb1e.png)

**Comment by rccess** [comment]
any chance to get the reply on this issue ?

**Comment by LucasBrazi06** [comment]
What do you me by proper condition?

**Comment by rccess** [comment]
i Need to send the issue in detail ?

**Comment by LucasBrazi06** [comment]
I don't know what's wrong with the email ;)

**Comment by rccess** [comment]
The Notification comes to admin when Charging Station get Connected or Registered 

The Email Template not coming properly, not html loading, original raw email coming to admin mail id

issue might be in https://github.com/sap-labs-france/ev-server/blob/c603f935ef3c33ae5006c4dfe1de05115dbdbf93/src/notification/email/EMailNotificationTask.ts#L79

This is the screenshot below

![image](https://user-images.githubusercontent.com/32220165/141085413-596b1a7a-d4c6-4573-b88b-72fb9fa6c60f.png)

**Comment by LucasBrazi06** [comment]
Ah ok, I got it.
@rmangin-fr Could you have a look and test the email notif on a GMail account?
Thanks!

**Comment by rmangin-fr** [comment]
Tested with no reproducible case.
GMail shows the ChargingStationRegistered notification as expected
See screenshot bellow:
![image](https://user-images.githubusercontent.com/59734752/141132079-9b156fd2-4522-4a52-87ce-255b6c20bfeb.png)

**Comment by rmangin-fr** [comment]
German language tested as well with no error:
![image](https://user-images.githubusercontent.com/59734752/141132458-b8cd5dd4-a63f-438b-abbb-5885128e3400.png)

**Comment by rmangin-fr** [comment]
Hi,
Here is the English evidence of not reproducible:
![image](https://user-images.githubusercontent.com/59734752/141144027-2e13f908-b034-487b-8972-7de56e673499.png)

**Comment by rccess** [comment]
Smtp compatibility might be ?

Can you please share your config file? Might be i am missing something
there ?

**Comment by LucasBrazi06** [comment]
Not a lot to share:

<img width="525" alt="2021-11-18_09-26-27" src="https://user-images.githubusercontent.com/25266945/142379094-9aa32497-38fd-4ea0-9c89-286026453a7a.png">

**Comment by LucasBrazi06** [comment]
Let me know if your problem is solved.
