### ISSUE TITLE
Simulator charging station remote start request getting rejected by the ev-server

### ISSUE THREAD

**Issue by rccess** [sap-labs-france/ev-server#3141]
Hello team

i am trying to run ev-simulator to test 

but getting the following error 

![image](https://user-images.githubusercontent.com/32220165/144466705-4e760178-616e-4cfd-a271-3f0fd22c5784.png)

![image](https://user-images.githubusercontent.com/32220165/144466771-e0fa2a7c-1e37-4f3d-9ed6-ed65c587b64c.png)

logs

![image](https://user-images.githubusercontent.com/32220165/144467531-6e68b984-fbbf-4724-8bf1-cb3e31799501.png)

what may be the possible reason ?

**Comment by LucasBrazi06** [comment]
When you do a remote start, the simulator should send an Authorize OCPP message to the backend to check the RFID card.
Is there any other logs?
