### ISSUE TITLE
EV Simulator package not running  

### ISSUE THREAD

**Issue by rccess** [sap-labs-france/ev-server#3184]
Hello team,

ev-simulator package not running with the following error

node: 'v16.13.1',
 npm: '8.3.0' 

![image](https://user-images.githubusercontent.com/32220165/146574184-4a7f57c9-4f59-4ad6-8255-8a8d47401a74.png)

Please do advise 

thank you

**Comment by rccess** [comment]
any update on this issue ?

**Comment by LucasBrazi06** [comment]
Sorry for the delay, Christmas holiday ;-)!
I just found the issue which was a package upgrade.
I just provided a fix in master.
