### ISSUE TITLE
anyway to reduct tokenID length for charging station

### ISSUE THREAD

**Issue by rccess** [sap-labs-france/ev-server#3229]
Hello team,

We are facing some issue to put the charging station url in machine since machine have some maximum input limitation

is there any way to short the token id and tenant id 

ws://xxxxxx.live:8010/OCPP16/611e3b5a0961c75f3f22752d/61d6aa769321087dd03a5cb7/ABC-DC-30KW

can we do this like 

ws://xxxxxx.live:8010/OCPP16/611e3b5/61d6w3/ABC-DC-30KW

Please do advise 

Thank You

**Comment by LucasBrazi06** [comment]
We had the same problem with 2 brand of charging stations and we forced them to increase the size of the URL.
URL can be long up to 2k chars.
