### ISSUE TITLE
Bug - inactivity status - wrong color

### ISSUE THREAD

**Issue by ClaudeROSSI** [sap-labs-france/ev-server#3231]
The inactivity status is suspicious when running automated tests (same meter values / same consumptions, but with a different pricing model).

Here is an example where we get unpredictable colours!

<img width="1484" alt="2022-01-07_09-39-01" src="https://user-images.githubusercontent.com/26900551/148516799-20deaab7-1eb2-414f-ae8f-9642f060e5d5.png">

**Comment by LucasBrazi06** [comment]
The color depends on the type of Charging Station.
We didn't put a legend in the UI yet.
Check Utils.getEndOfChargeNotificationIntervalMins()

**Comment by ClaudeROSSI** [comment]
good to know!
So, this is not a bug!

p.s.: I was trying to generate a colorful-rainbow inactivity status ;)

**Comment by LucasBrazi06** [comment]
> p.s.: I was trying to generate a colorful-rainbow inactivity status ;)

LOL, you will miss some color :D !!!
