### ISSUE TITLE
Pricing based on user groups/segments

### ISSUE THREAD

**Issue by patrick-nurt** [sap-labs-france/ev-server#3243]
Hi SAP Labs,

Great project!

Is it possible to do specific pricing for a group of users?

Best regards
Patrick

**Comment by LucasBrazi06** [comment]
Hi Patrick,
Thanks!
This will be our next dev :-)
For the time being we are enhancing the pricing with constraints.
This topic will start end of February / March.
Serge.

**Comment by patrick-nurt** [comment]
Awesome :-)
