### ISSUE TITLE
Wrong escaping of HTML tags in long texts (in integration settings)

### ISSUE THREAD

**Issue by ClaudeROSSI** [sap-labs-france/ev-server#3253]
Tags are not escaped anymore:

Example below tag BR!

![image.png](https://images.zenhubusercontent.com/5fa82ce7552e0aed8eb43377/05ef5165-6793-477b-87f5-12c79309aa16)

**Comment by ClaudeROSSI** [comment]
@LucasBrazi06 : Tu sais d'ou ca peux venir?

**Comment by LucasBrazi06** [comment]
Just merged a PR that fixed it ;-)

**Comment by ClaudeROSSI** [comment]
We also have a problem with the text of the confirmation dialogs!

![image](https://user-images.githubusercontent.com/26900551/150546680-cbc66b79-e1f5-478f-bde4-1a287a85c40c.png)

**Comment by LucasBrazi06** [comment]
> We also have a problem with the text of the confirmation dialogs!
> 
> ![image](https://user-images.githubusercontent.com/26900551/150546680-cbc66b79-e1f5-478f-bde4-1a287a85c40c.png)

In the i18n we could put an Array of strings, 1 per line and detect in the dialog the multiline text and add the right HTML tags in that case (<br/>.)
What do you think?

**Comment by ClaudeROSSI** [comment]
> > We also have a problem with the text of the confirmation dialogs!
> > ![image](https://user-images.githubusercontent.com/26900551/150546680-cbc66b79-e1f5-478f-bde4-1a287a85c40c.png)
> 
> In the i18n we could put an Array of strings, 1 per line and detect in the dialog the multiline text and add the right HTML tags in that case (`<br/>`.) What do you think?

Let me check ... I was using the HTML Tag escaping in the billing as well (when asking to confirm the billing activation). This was working fine at that time. I need to understand why!

**Comment by ClaudeROSSI** [comment]
> > > We also have a problem with the text of the confirmation dialogs!
> > > ![image](https://user-images.githubusercontent.com/26900551/150546680-cbc66b79-e1f5-478f-bde4-1a287a85c40c.png)
> > 
> > 
> > In the i18n we could put an Array of strings, 1 per line and detect in the dialog the multiline text and add the right HTML tags in that case (`<br/>`.) What do you think?
> 
> Let me check ... I was using the HTML Tag escaping in the billing as well (when asking to confirm the billing activation). This was working fine at that time. I need to understand why!

The root cause of the new behavior is a security fix from Siwar to prevent xss injection attacks!

![image](https://user-images.githubusercontent.com/26900551/150760144-0c9152d7-a084-400a-a91f-6d51354f15a0.png)

**Comment by ClaudeROSSI** [comment]
> > > > We also have a problem with the text of the confirmation dialogs!
> > > > ![image](https://user-images.githubusercontent.com/26900551/150546680-cbc66b79-e1f5-478f-bde4-1a287a85c40c.png)
> > > 
> > > 
> > > In the i18n we could put an Array of strings, 1 per line and detect in the dialog the multiline text and add the right HTML tags in that case (`<br/>`.) What do you think?
> > 
> > 
> > Let me check ... I was using the HTML Tag escaping in the billing as well (when asking to confirm the billing activation). This was working fine at that time. I need to understand why!
> 
> The root cause of the new behavior is a security fix from Siwar to prevent xss injection attacks!
> 
> ![image](https://user-images.githubusercontent.com/26900551/150760144-0c9152d7-a084-400a-a91f-6d51354f15a0.png)

@LucasBrazi06 : We have the same security issue with the EULA text. I would therefore suggest reverting the fix from Siwar (for now). 
What do you think?

Here is the previous behavior!
![image](https://user-images.githubusercontent.com/26900551/150765988-c49c89d6-28ee-4bbf-a021-f39c377449b0.png)

**Comment by LucasBrazi06** [comment]
> @LucasBrazi06 : We have the same security issue with the EULA text. I would therefore suggest reverting the fix from Siwar (for now).
> What do you think?

I agree as the source of the HTML is not provided from the end-user but by the application itself.
We can think of the multi line in the i18n mid-term to remove the HTML tags in it which is not nice.
