### ISSUE TITLE
Align migrated ABAC endpoints

### ISSUE THREAD

**Issue by Ramzay** [sap-labs-france/ev-server#3255]
We have migrated 7 endpoints to ABAC, no it's time to align the endpoints with what we have learned improved during the migration:
- [x] CompanyService
- [x] Site Service
- [x] SiteAreaService
- [x] TagService
- [x] CarService
- [x] RegistrationTokenService

We will be using AssetService as a reference.

Depending on the complexity other issues / PR will be opened.

**Comment by LucasBrazi06** [comment]
@Ramzay Add more details in the issue/PRs about the endpoint you have migrated ;-)
