### ISSUE TITLE
Billing - remove feature toggle for user sync

### ISSUE THREAD

**Issue by ClaudeROSSI** [sap-labs-france/ev-server#3304]
User synchronization is now fully lazy.

The corresponding feature toggle is OFF for more than one year now.
The corresponding code (and the feature toggle) can now be removed safely.

**Comment by LucasBrazi06** [comment]
@ClaudeROSSI Should have I to remove the scheduled tasks from the conf in Prod/QA?
- SynchronizeBillingUsersTask
- SynchronizeBillingInvoicesTask

**Comment by ClaudeROSSI** [comment]
> I did it for PROD (aws) only.
> When the config still have these tasks we simply log an error in the master tenant.

I did it for PROD (aws) only.
When the config still have these tasks we simply log an error in the master tenant.
