### ISSUE TITLE
Current threshold do not match quality engagement

### ISSUE THREAD

**Issue by KinzaBS** [sap-labs-france/ev-server#3370]

**Comment by KinzaBS** [comment]
![image](https://user-images.githubusercontent.com/77412071/154981765-d160ec52-dd4c-4e17-868b-dc34f0f8aff5.png)

AFIREV : 
Charging sessions that lasted more than 2 minutes and provided energy greater than 0.5 kWh are considered to be “successfully started”.

Current sessions in error are not matching this french quality engagement.

**Comment by LucasBrazi06** [comment]
@ClaudeROSSI New params in Tenant settings?
