### ISSUE TITLE
I am trying to run this on Node 16.14.0, NPM 8.3.1 and MongoDB 4.4.13, but I am facing the same error.

### ISSUE THREAD

**Issue by dignitech-rakesh** [sap-labs-france/ev-server#3405]
I am trying to run this on Node 16.14.0, NPM 8.3.1 and MongoDB 4.4.13, but I am facing the same error.
<img width="781" alt="Screenshot 2022-03-08 at 7 44 35 PM" src="https://user-images.githubusercontent.com/79455126/157255198-48870f83-7ba4-456a-b74b-05cf1f2860bc.png">
<img width="965" alt="Screenshot 2022-03-08 at 7 44 53 PM" src="https://user-images.githubusercontent.com/79455126/157255269-214ecf80-992c-43f4-9576-f198e95bed02.png">

Please advise.

_Originally posted by @dignitech-rakesh in https://github.com/sap-labs-france/ev-server/issues/3397#issuecomment-1061822991_

**Comment by LucasBrazi06** [comment]
Dups of #3397 ?

**Comment by dignitech-rakesh** [comment]
> Dups of #3397 ?

Yes, but I am curious to know that will it specifically work on npm 8.5.2 version?

**Comment by LucasBrazi06** [comment]
You are using 8.3.1 here, not 8.5.2
