### ISSUE TITLE
https problem

### ISSUE THREAD

**Issue by aliuysal60** [sap-labs-france/ev-server#3429]
Hello,
I want to run rest server https and ocpp server wss, but when I set protocol https in config.json, servers cannot be reached. rest server and ocpp server are not responding.

What is the method to get it working? below is my config example.
I have defined ssl certificates in ServerUtils.ts but the problem persists.

` "CentralSystems": [
    {
      "type": "ocpp",
      "implementation": "soap",
      "protocol": "https",
      "host": "myhost",
      "port": 8000,
      "debug": false
    },
    {
      "type": "ocpp",
      "implementation": "json",
      "protocol": "wss",
      "host": "myhost",
      "port": 8010,
      "keepaliveinterval": 30,
      "debug": false
    }
  ],
  "CentralSystemRestService": {
    "protocol": "https",
    "host": "myhost",
    "port": 8888,
    "userTokenKey": "mytoken",
    "userTokenLifetimeHours": 12,
    "userDemoTokenLifetimeDays": 365,
    "userTechnicalTokenLifetimeDays": 365,
    "passwordWrongNumberOfTrial": 3,
    "passwordBlockedWaitTimeMin": 5,
    "captchaSecretKey": "my-secret",
    "captchaScore": 0.25,
    "debug": false
  },
  "CentralSystemFrontEnd": {
    "protocol": "https",
    "host": "my-host",
    "port": 8888
`

**Comment by LucasBrazi06** [comment]
We don't have really the use of TLS in local env so it's not maintained.
If you want to provide fixes, feel free.

**Comment by UBT-FJ** [comment]
hello @aliuysal60 

did you find any solution for this?
