### ISSUE TITLE
EV-simulator not working only waiting

### ISSUE THREAD

**Issue by mytrkr0** [sap-labs-france/ev-server#3442]
Hi Mr.Serge 

i started ev-simulator npm start and it is started.
![image](https://user-images.githubusercontent.com/101884800/160791057-74a3a574-f531-483b-a69a-698c0488fca1.png)

but dashboard is not updating.

![image](https://user-images.githubusercontent.com/101884800/160791378-ee45e16f-3421-4fc9-a05f-fbf054a1be58.png)

my config.json file is 

```json
{
  "supervisionURLs": [
    "ws://localhost:8010/OCPP16/623c52f5341fffb3b6ed2310"
  ],
  "distributeStationsToTenantsEqually": true,
  "performanceStorage": {
    "enabled": true
  },
  "chargingStationsPerWorker": 1,
  "workerProcess": "workerSet",
  "workerPoolMinSize": 4,
  "workerPoolMaxSize": 16,
  "stationTemplateURLs": [
    {
      "file": "siemens.station-template.json",
      "numberOfStations": 1
    },
    {
      "file": "keba.station-template.json",
      "numberOfStations": 2
    },
    {
      "file": "abb.station-template.json",
      "numberOfStations": 2
    },
    {
      "file": "evlink.station-template.json",
      "numberOfStations": 4
    },
    {
      "file": "schneider.station-template.json",
      "numberOfStations": 1
    }
  ],
  "logStatisticsInterval": 0,
  "logFile": "combined.log",
  "logErrorFile": "error.log"
}
```

and Central Systems config is

```json
  "CentralSystems": [
    {

      "type" : "ocpp",
       "implementation": "json",
      "protocol": "ws",
      "host": "localhost",
      "port": 8010,
      "debug": false
    }
  ]
```

by the way what is supervisionURLs in config.json and how can i fill it so can you type  like #3048 

![image](https://user-images.githubusercontent.com/101884800/160793125-b66d9449-35e7-4704-9cdf-5038eea1bf7d.png)

thank you for your answer

**Comment by mytrkr0** [comment]
![image](https://user-images.githubusercontent.com/101884800/160803192-9b4dbf1d-7944-4bcd-a21f-6a6086ee4342.png)

**Comment by nazlikrmn** [comment]
If you haven't made any changes on the connection procedure, I think that the url you entered in the supervision URLs might be the problem. example pattern: 
OCPP16/tenantid/tokenid/chargingstation
Did you try change that?

**Comment by mytrkr0** [comment]
tenant and organisation are they equal ?

**Comment by Zakichanu** [comment]
Hi, can you tell me how did you fix this?

**Comment by Zakichanu** [comment]
Just saw #3048 I understand the problem
