### ISSUE TITLE
Smart charging - poor error message in mails and notification

### ISSUE THREAD

**Issue by ClaudeROSSI** [sap-labs-france/ev-server#3451]
Please  get rid of the message mentioning the number of attempts!!!

This makes no sense.

A root cause would be helpful instead ... but I'm not sure we actually know what happened!

<img width="810" alt="2022-04-05_08-00-16" src="https://user-images.githubusercontent.com/26900551/161688809-eb0e1107-e977-4cf3-9348-52e39eb6544e.png">

**Comment by LucasBrazi06** [comment]
Done
