### ISSUE TITLE
Ev-Server | Rest Api » chargingstation-delete » Error

### ISSUE THREAD

**Issue by mytrkr0** [sap-labs-france/ev-server#3483]
Hello everyone! I tried some function on ev-server but i receive some error like below. it is seems about schema but I don't now exactly. 

What is the problem?

Action: Delete Station
Error: "Can't resolve reference chargingstation#/definitions/id from id chargingstation-delete"

![image](https://user-images.githubusercontent.com/101884800/164224720-2d3c5b72-24b5-462d-a1fd-2f8972da8c04.png)

**Comment by LucasBrazi06** [comment]
I don't have any error like this one in master-qa.
Check the schema files (src/assets/schemas/chargingstation/chargingstation.json)

**Comment by mytrkr0** [comment]
Thank you very much.

Actually I looked after you said my schema i used wrong schema but i update with master-qa json and it worked.
