### ISSUE TITLE
Missing porperty 'JsonEndpoint.targetPort' in config.json

### ISSUE THREAD

**Issue by Gregor193** [sap-labs-france/ev-server#3499]
Hello 
When starting the server I get the following error message: 

![MissingPropertyJsonEndpointtargetPort](https://user-images.githubusercontent.com/86152408/165459705-03680d9d-f778-4f63-af34-4087cb0ef719.PNG)

Attached is my config.json

[config.json.txt](https://github.com/sap-labs-france/ev-server/files/8569622/config.json.txt)

I have set the port in config. Why do I get an error message for this? Have I made a beginner's mistake here?

**Comment by mytrkr0** [comment]
Hello,

You can add to config.json

```json
"JsonEndpoint": {
    "baseSecureUrl": "ws://192.168.0.10:8010"
  }
```

instead change it as below

```json
"JsonEndpoint": {
    "baseSecureUrl": "ws://192.168.0.10:8010",
    "targetPort" : "<YOUR_TARGET_PORT>"
  },
```
like this

```json
"JsonEndpoint": {
    "baseSecureUrl": "ws://192.168.0.10:8010",
    "targetPort" : 8010
  },
```

I wish conveniences

**Comment by Gregor193** [comment]
Thank you, it worked 
Do you also have any advice regarding the warning monitoring? 
Thanks in advance

**Comment by LucasBrazi06** [comment]
> Thank you, it worked Do you also have any advice regarding the warning monitoring? Thanks in advance

It is used in production when you have Prometheus as a monitoring tools, then not mandatory.
