### ISSUE TITLE
Updates from Github

### ISSUE THREAD

**Issue by Gregor193** [sap-labs-france/ev-server#3523]
Hello together, 
is there a possibility to keep the files of the server and the dashboard of Github up to date by a command in the console?

**Comment by LucasBrazi06** [comment]
What do you mean?

**Comment by Gregor193** [comment]
I mean that when improvements are made to the server and dashboard files, whether you can update them while the server is running.

**Comment by LucasBrazi06** [comment]
We have CI/CD pipelines to test, build and deploy in QA and Prod.
Whenever we make a change in a branch, the corresponding pipeline is triggered and the new version is deployed.
