### ISSUE TITLE
How can i get user id through rest API (is there API service)

### ISSUE THREAD

**Issue by mytrkr0** [sap-labs-france/ev-server#3533]
Hello Mr. Serge i looked RestApi services with postman but i couldn't find how can I get user id.

**Comment by LucasBrazi06** [comment]
I don't get what you meant :-)
But you can use Swagger: http://localhost:8002/v1/docs/
8002 is the port of your REST server.

**Comment by mytrkr0** [comment]
Thank you for your answer Mr. Serge. 

Actually i mean was; i can get "User information" from "**Rest Server**" by use "**user ID**".

But when I login to server with **Rest**; there isn't any "**User ID**" related with my **e-mail address** in response, only there is **token**.

In this situation i can't learn information of login person. So should be there "**user ID too**" with "**token**" in Login Successful response.

I hope I was clear :)

**Comment by LucasBrazi06** [comment]
The user ID is in the token.
You can decode it.

**Comment by mytrkr0** [comment]
Glad to hear that Mr Serge :)

How can i find this decode formula?

**Comment by mytrkr0** [comment]
JWT,  okay i found it

Thank you for all Mr. Serge

**Comment by LucasBrazi06** [comment]
With that? ;-)
https://jwt.io/

**Comment by mytrkr0** [comment]
Definitely yes :)

Thank you repeatedly.
