### ISSUE TITLE
Car catalog update from EV Database

### ISSUE THREAD

**Issue by mytrkr0** [sap-labs-france/ev-server#3565]
Hello Mr. Serge 

How can I get car cars from database. 

There are to parameters in EV Database chapter but Is it enoug?

I want to learn database model and other requirements

Thank you for all

**Comment by LucasBrazi06** [comment]
You'll have to buy a licence here:
https://ev-database.org/#sort:path~type~order=.rank~number~desc|range-slider-range:prev~next=0~1200|range-slider-acceleration:prev~next=2~23|range-slider-topspeed:prev~next=110~450|range-slider-battery:prev~next=10~200|range-slider-towweight:prev~next=0~2500|range-slider-fastcharge:prev~next=0~1500|paging:currentPage=0|paging:number=9
