### ISSUE TITLE
Invoice bug: Autostart transactions not invoiced 

### ISSUE THREAD

**Issue by testocpp** [sap-labs-france/ev-server#3569]
Hello,

We tested the system under the use case when a charger is configured to an autostart mode with particular RFID card which needs to be billed for all transactions. Under this use case transaction is tracked but system never invoiced and no payment is deducted. When RFID card is tapped on other chargers system is working as intended. 

Cheers

**Comment by LucasBrazi06** [comment]
We don't know how this autostart is working but it must call the backend with all OCPP messages (Auth, Start Transaction, Meter Values, Stop Transaction, Status Notification...)
Provide more information.
