### ISSUE TITLE
Login URL showing 404 error

### ISSUE THREAD

**Issue by dignitech-rakesh** [sap-labs-france/ev-server#3580]
I have configured both ev-dashboard and ev-server on my server, and it seems to be accessible from the URL. However, when try to log in from the dashboard panel, it shows 404 error in the console.
<img width="550" alt="Screenshot 2022-06-03 at 1 49 20 PM" src="https://user-images.githubusercontent.com/79455126/171816701-dc6951cf-23a9-487f-93ba-cb6032ccf44d.png">

I checked the pm2 log also, and this is what I found:
<img width="884" alt="Screenshot 2022-06-03 at 1 49 56 PM" src="https://user-images.githubusercontent.com/79455126/171816804-d17e9c33-7cbe-40e6-9c87-bff5ac4841cd.png">

**Comment by xEmanuelx** [comment]
I have the same problem.
@LucasBrazi06 Could you give us support ?

**Comment by LucasBrazi06** [comment]
> I have the same problem.
> @LucasBrazi06 Could you give us support ?

Have you checked my reply?
