### ISSUE TITLE
Struggling with ChargingStationCapabilities

### ISSUE THREAD

**Issue by vladajanjanin** [sap-labs-france/ev-server#3596]
Hello.
We've been trying to setup smart charging in our system. Everything else works well.
<img width="513" alt="Screenshot 2022-06-09 at 19 08 34" src="https://user-images.githubusercontent.com/36325315/172906458-9709f217-6a80-4612-adc9-485f95592937.png">

If I understood it right from the frontend, it asks for: chargingStation.capabilities.supportChargingProfiles
I'm actually not sure how ChargingStationCapabilities object in ChargingStation is created, since it's "null" in our database.
We're not sure if we've been setting up our charging stations correctly, or we missed something. Everything else worked fine until now. 

Thanks in advance.

**Comment by LucasBrazi06** [comment]
It's provided by charging station templates that are not public.
You have to build you own.
We do not provide support on this for free, sorry!
