### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by adraoo** [sap-labs-france/ev-server#3616]
Hello,

Why are they 6 critical vulnerabilities and 14 high vulnerabilities after installing the last libraries ?

Sincerely

https://www.dropbox.com/s/6iaghkw1lfet33c/Screenshot%202022-06-15%20at%2013.30.14.png?dl=0

**Comment by LucasBrazi06** [comment]
We know and we planned to update the libs soon.
Thanks for reporting.
