### ISSUE TITLE
Password Reset with REST API 

### ISSUE THREAD

**Issue by mytrkr0** [sap-labs-france/ev-server#3617]
Hello Mr. Serge

How can i change password with rest api (by basic user)

Could you share relating to rest api endpoint (I couldn't find in postman collections).

If it is impossible would you say why?

**Comment by LucasBrazi06** [comment]
Postman is not fully maintained, we will update it.
Check the Swagger API.
<REST_SERVER>/v1/docs

**Comment by mytrkr0** [comment]
Thank you Mr. Serge
