### ISSUE TITLE
Billing problem

### ISSUE THREAD

**Issue by aliuysal60** [sap-labs-france/ev-server#3787]
Hello;
The normally running billing service has stopped working. Is there any information on this subject? Should I look on my side?

The charging process starts and finishes successfully, I see the price graph increase in the statistics, but the invoices do not appear in the and there is no movement on the Stripe side.

I started having this problem with version 2.6.8

I can't see any records in the logs. Neither on the tenant's and admin side

**Comment by Zakichanu** [comment]
HI, do you have any advice how to work this out, I have the same issue...

**Comment by aliuysal60** [comment]
No, I couldn't find a solution.
Maybe @LucasBrazi06 can help.

**Comment by LucasBrazi06** [comment]
The current version is 2.7.3, do you have the same issue?

**Comment by aliuysal60** [comment]
I see the latest version 2.6.10

**Comment by Zakichanu** [comment]
> The current version is 2.7.3, do you have the same issue?

In my case, i'm in the 2.7.3 version

**Comment by LucasBrazi06** [comment]
The only way to find out what's wrong is the logs!

**Comment by Zakichanu** [comment]
I look through the logs and get this : 
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/49374657/200194502-48ba5701-16e9-4c70-b655-c6ae3e620767.png">

I tried the payment on a charging station from the ev-simulator, I search what it can be, I didn't find anything relevant

Thanks in advance

**Comment by Zakichanu** [comment]
A little update, my customer is now accepted and I don't have any issue with it from now on.

So I started to check everything about my stripe account, everything is good about it.

My admin account of the test organisation have credit card affiliate to his account : 
<img width="667" alt="image" src="https://user-images.githubusercontent.com/49374657/200670609-732f318f-0c6e-498f-b10b-88acb763df09.png">

I then, checked the session and on the tab of refunding, we can see here, we got all my transcations in status "Not Submitted", in stripe the logs are not calling the endpoint to retrieve payment...
<img width="839" alt="image" src="https://user-images.githubusercontent.com/49374657/200670314-f177c321-d644-43e0-a282-9ebbe089ed30.png">

Any hint to solve this? @LucasBrazi06 @ClaudeROSSI

**Comment by ClaudeROSSI** [comment]
> I look through the logs and get the same error on two different actions :
> 
> * BillingPaymentMethods
> 
> <img alt="image" width="1144" src="https://user-images.githubusercontent.com/49374657/200194502-48ba5701-16e9-4c70-b655-c6ae3e620767.png">
> 
> * BillingSynchronizeUser
> 
> <img alt="image" width="1105" src="https://user-images.githubusercontent.com/49374657/200194866-f9979de2-1085-4591-adab-d7b5e900ed83.png">
> 
> I tried the payment on a charging station from the ev-simulator, I search what it can be, I didn't find anything relevant
> 
> Thanks in advance

The screenshot shows that the customerID is inconsistent. This means that someone (a STRIPE administrator) went to the stripe account and deleted the customer (or someone change the settings to reference a different STRIPE account). The consequence is that the user on the emobility side is orphan and references something which does not exist anymore on the stripe side.

You should normally never get to that situation. The workaround however is to navigate to the user list and force the synchronization with the billing system.

<img width="322" alt="2022-11-08_22-01-47" src="https://user-images.githubusercontent.com/26900551/200674755-0245e0c0-ad8f-473e-8d02-2e1521ed61dc.png">

This will create a new customer in STRIPE and set again the customerID to a valid value.
However, the former user history (if any) is lost.

Hope this helps,
Claude

**Comment by ClaudeROSSI** [comment]
> A little update, my customer is now accepted and I don't have any issue with it from now on.
> 
> So I started to check everything about my stripe account, everything is good about it.
> 
> My admin account of the test organisation have credit card affiliate to his account : <img alt="image" width="667" src="https://user-images.githubusercontent.com/49374657/200670609-732f318f-0c6e-498f-b10b-88acb763df09.png">
> 
> I then, checked the session and on the tab of refunding, we can see here, we got all my transcations in status "Not Submitted", in stripe the logs are not calling the endpoint to retrieve payment... <img alt="image" width="839" src="https://user-images.githubusercontent.com/49374657/200670314-f177c321-d644-43e0-a282-9ebbe089ed30.png">
> 
> Any hint to solve this? @LucasBrazi06 @ClaudeROSSI

I'm afraid, I do not understand the question here.
There is no link between STRIPE and the refunding capabilities that Open e-Mobility offers.
These are two different layers!

Let me know what you think!
Regards
Claude

**Comment by Zakichanu** [comment]
> > I look through the logs and get the same error on two different actions :
> > 
> > * BillingPaymentMethods
> > 
> > <img alt="image" width="1144" src="https://user-images.githubusercontent.com/49374657/200194502-48ba5701-16e9-4c70-b655-c6ae3e620767.png">
> > 
> > * BillingSynchronizeUser
> > 
> > <img alt="image" width="1105" src="https://user-images.githubusercontent.com/49374657/200194866-f9979de2-1085-4591-adab-d7b5e900ed83.png">
> > I tried the payment on a charging station from the ev-simulator, I search what it can be, I didn't find anything relevant
> > Thanks in advance
> 
> The screenshot shows that the customerID is inconsistent. This means that someone (a STRIPE administrator) went to the stripe account and deleted the customer (or someone change the settings to reference a different STRIPE account). The consequence is that the user on the emobility side is orphan and references something which does not exist anymore on the stripe side.
> 
> You should normally never get to that situation. The workaround however is to navigate to the user list and force the synchronization with the billing system.
> 
> <img alt="2022-11-08_22-01-47" width="322" src="https://user-images.githubusercontent.com/26900551/200674755-0245e0c0-ad8f-473e-8d02-2e1521ed61dc.png">
> 
> This will create a new customer in STRIPE and set again the customerID to a valid value. However, the former user history (if any) is lost.
> 
> Hope this helps, Claude

Hi @ClaudeROSSI,

Thanks for this response, I made this process and it worked, I have to test it out now on a session.



> > A little update, my customer is now accepted and I don't have any issue with it from now on.
> > So I started to check everything about my stripe account, everything is good about it.
> > My admin account of the test organisation have credit card affiliate to his account : <img alt="image" width="667" src="https://user-images.githubusercontent.com/49374657/200670609-732f318f-0c6e-498f-b10b-88acb763df09.png">
> > I then, checked the session and on the tab of refunding, we can see here, we got all my transcations in status "Not Submitted", in stripe the logs are not calling the endpoint to retrieve payment... <img alt="image" width="839" src="https://user-images.githubusercontent.com/49374657/200670314-f177c321-d644-43e0-a282-9ebbe089ed30.png">
> > Any hint to solve this? @LucasBrazi06 @ClaudeROSSI
> 
> I'm afraid, I do not understand the question here. There is no link between STRIPE and the refunding capabilities that Open e-Mobility offers. These are two different layers!
> 
> Let me know what you think! Regards Claude

To respond to this, I just realize the misunderstanding I made, thanks to you for this reply!


I will update you if there any other issue.

**Comment by Zakichanu** [comment]
Hi again,

I was wondering if the transaction are working even if it is a charging station from the simulator?

Thanks in advance

**Comment by ClaudeROSSI** [comment]
> Hi again,
> 
> I was wondering if the transactions are working even if it is a charging station from the simulator?
> 
> Thanks in advance

Transactions work properly as soon as they receive consistent OCPP meter values (with consistent data). The simulator is supposed to mimic the behaviour of regular charging stations. Right? 
When it does its job properly, there is no way server-side to know whether the OCPP calls are coming from a real charger or a fake one. You could even trigger the pricing and billing layers if the corresponding modules are properly configured.

Claude

**Comment by Zakichanu** [comment]
Hi! 

Ok, thanks for your response, I will try with a simulator ASAP

**Comment by Zakichanu** [comment]
Hi again @ClaudeROSSI,

I tried with ev-simulator. I ran a session on a charging station with a price of 2€/session as you can see here (the data are biased but I don't think it is the most important thing here) : 
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/49374657/202858100-4be337e7-a81f-47d1-a089-2844f53a3a9a.png">

But there is nothing happening on my stripe dashboard...
<img width="348" alt="image" src="https://user-images.githubusercontent.com/49374657/202858124-e978afe6-ec94-49df-a6c1-e51178d402fb.png">

I don't see where the problem can be, set apart, maybe, the fact that I am using a simulator instead of a real session with a real car.

**Comment by Zakichanu** [comment]
Hi again,

I am still dealing with this issue... If there is any solution (or not), hit me up!
