### ISSUE TITLE
Remote REstart not working

### ISSUE THREAD

**Issue by KinzaBS** [sap-labs-france/ev-server#3792]

**Comment by KinzaBS** [comment]
A customer is complaining :

- Car is charging and you remote stop -> status in finishing
- when you need to start transaction again, button remote start is missing (it has been there before)
![image](https://user-images.githubusercontent.com/77412071/185334405-da1ead5e-e672-4fff-88b3-6d5f57edb868.png)

**Comment by Ramzay** [comment]
Hello @KinzaBS, the start charging button is only available / allowed  (make sense) when the status is either:
- Available
- Preparing
- Reserved

The Finishing status is temporary, the status that comes afterwards should be 'Available' (which allows a start charge)

Let me know :)

**Comment by ClaudeROSSI** [comment]
We had a concrete use-case where restarting the charge while being in status FINISHING makes sense.
So the action is now enabled again.
