### ISSUE TITLE
Sessions History from dashboard

### ISSUE THREAD

**Issue by KinzaBS** [sap-labs-france/ev-server#3830]

**Comment by KinzaBS** [comment]
In order to facilitate Debugging, we would need to filter directly from the "Charging Station" to the sessions history of the selected charging station. 
![image](https://user-images.githubusercontent.com/77412071/187167821-5ca3b63e-b12a-4fe3-9226-0fdb42bff401.png)

**Comment by ClaudeROSSI** [comment]
@mahdibenromdhane : Can you double check it. The new link does not work with version 2.7.2
