### ISSUE TITLE
Errors with getConfiguration with charging stations

### ISSUE THREAD

**Issue by Zakichanu** [sap-labs-france/ev-server#3954]
Hi,

I am currently working with your app and I was trying to add a charging station on a test organization which has 4 connectors.

The bootNotification works well, but, the OcppGetConfiguration is never done and when I try to change configuration, we got this error : 
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/49374657/199311041-edab1996-7b0a-4e4e-b6d2-875735a00d91.png">

Are you familiar with this?

**Comment by Zakichanu** [comment]
The thing is, I want to get the logs of the communication between central server and the charging station, how can i see it?

**Comment by Justin9302** [comment]
because the hardware(CP) is not fully comply with the OCPP protocol, which should reply with the message like this: getconfigurationkeys:{knwon keys},{unknown keys}.
