### ISSUE TITLE
Email Not Arrive to gmail 

### ISSUE THREAD

**Issue by An-nasMs1817120893** [sap-labs-france/ev-server#4051]
Hi, this might sound stupid, but I'm not able to get the verification email after register my account. 

i have registered my account and it was successful , you can see the mongdb log as shown below 

<img width="759" alt="image" src="https://user-images.githubusercontent.com/113960675/212534683-1bab2eba-cdb9-4a6e-a874-09aafb55155c.png">

However, after that it said that I need to wait for admin to verify my account and check my email however I did not receive any email

below is the log output from mongo db if I tried to log in without verified my account ( I mean how can I verify my account if the email is not arriving in my gmail right ? )

<img width="853" alt="Mongodb atlas log" src="https://user-images.githubusercontent.com/113960675/212534585-4a73010f-98f9-463e-af85-322acb9eb5fe.png">

can someone help me pls , I have spent countless hours trying to solve this , I really need some help :( 

if possible can someone share their config.json file snippets so I can follow pls :( 

I have read the issues which are completely similar to mine however the issue was closed and no direct solution was provided , pls help me :(

thank you.

**Comment by Zakichanu** [comment]
Hi,

You need to configure an SMTP server to allow your app to send emails. For your case, if you want to allow the user the authentication in a different way, you can just go to the the users table and change status `P` (for pending) to `A` (active)

Steps in detail : 
- Go to the users section of the default or the organization you want to log in : 
![image](https://user-images.githubusercontent.com/49374657/212542529-0c9fe43c-1631-4519-9c51-1c52538fa98b.png)

- Select the user want to activate access
- Then change the `status` attribute to `A` like follow
![image](https://user-images.githubusercontent.com/49374657/212542680-44b7ee52-3b55-446b-9b13-9f1714df2b5d.png)

Hope this helps :)

**Comment by An-nasMs1817120893** [comment]
WOW !! THANK YOU SO MUCH T_T !! this solved my issues !! :)

**Comment by Zakichanu** [comment]
Amazing! You can close this issue then

Have a nice day :D
