### ISSUE TITLE
HTTPS - SSL confirmation

### ISSUE THREAD

**Issue by AndyChriss123** [sap-labs-france/ev-server#4201]
Hello and thank you very much for your work!
I would like a confirmation with regard to SSL/HTTPS on the server side.>
In config you can find:

```
    "sslKey": "/home/h-----cs/CS--/------_com.key",
    "sslCert": "/home/h-----cs/CS--/------_com.crt",
    "sslCa": [],
```
But I can't see these values being called/used anywhere in the code. Is https connectivity a work in progress/ not provided or am I unaware of how to set this up?
I have secure communication with the dashboard from the outside but I can't establish https connection to server.
Once again, I don't want to waste anyone's time, I would just like a simple confirmation.
Thank you very much once again and I wish you the best of luck in whatever it is that you are doing!

**Comment by AndyChriss123** [comment]
I have managed with nginx as a reverse proxy with SSL enabled and configured. I understand that HTTPS is not a priority for dev environment from other such posts. If anybody needs help with this I'm willing to help out, just let me know.
All the best!

**Comment by samarasdelta** [comment]
Hello @AndyChriss123,
I seem to have the same problem. Could you describe the resolution steps for this particular issue?
Thanks in advance!

**Comment by AndyChriss123** [comment]
Hello,
On the dashboard side you can rewrite the startup script for start-ssl (or run-ssl i don't remember exactly) to include your certificate paths. For communication between central server and dashboard or central server and mobile I use nginx as a reverse proxy through which I encrypt the data using the same ssl certificates while maintaining http communication from the config files. I can upload the config files for server dashboard and nginx if you would like but It might be as late as tomorrow.
They have stated somewhere on github in an issue chat that ssl is not a high priority for them as it does not affect dev or something like that so this is only a solution that I came up with while facing this problem.
Good luck and have a great day!
